frameworkVersion: '3'
org: taylorjg
app: print-puz
service: print-puz

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-webpack

functions:
  scrape-puzzle-url:
    handler: src/scrape-puzzle-url.handler
    events:
      - httpApi:
          method: get
          path: /scrape-puzzle-url
  list-puzzles:
    handler: src/list-puzzles.handler
    events:
      - httpApi:
          method: get
          path: /list-puzzles
  parse-puzzle:
    handler: src/parse-puzzle.handler
    events:
      - httpApi:
          method: get
          path: /parse-puzzle
