service: print-puz

build:
  esbuild:
    bundle: true
    minify: true

provider:
  name: aws
  profile: taylorjg
  runtime: nodejs24.x
  httpApi:
    cors: true

functions:
  scrape-puzzle-url:
    handler: src/scrape-puzzle-url.handler
    events:
      - httpApi:
          method: get
          path: /scrape-puzzle-url
  list-puzzles:
    handler: src/list-puzzles.handler
    events:
      - httpApi:
          method: get
          path: /list-puzzles
  parse-puzzle:
    handler: src/parse-puzzle.handler
    events:
      - httpApi:
          method: get
          path: /parse-puzzle
